<?php

namespace Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-17 at 00:50:40.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Core\Controller::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core\Controller::redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core\Controller::requireLogin
     * @todo   Implement testRequireLogin().
     */
    public function testRequireLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
