<?php

namespace Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-17 at 00:50:39.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Error;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Core\Error::errorHandler
     * @todo   Implement testErrorHandler().
     */
    public function testErrorHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core\Error::exceptionHandler
     * @todo   Implement testExceptionHandler().
     */
    public function testExceptionHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
