<?php

namespace App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-23 at 16:43:02.
 */
class AuthTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Auth
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Auth;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers App\Auth::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Auth::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Auth::rememberRequestedPage
     * @todo   Implement testRememberRequestedPage().
     */
    public function testRememberRequestedPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Auth::getReturnToPage
     * @todo   Implement testGetReturnToPage().
     */
    public function testGetReturnToPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Auth::getUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
