<?php

namespace App;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-23 at 16:43:00.
 */
class FlashTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Flash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Flash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers App\Flash::addMessage
     * @todo   Implement testAddMessage().
     */
    public function testAddMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Flash::getMessages
     * @todo   Implement testGetMessages().
     */
    public function testGetMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
