<?php

namespace App\Controllers;

include_once '../App/Controllers/Post.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-26 at 17:12:27.
 */
class PostTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Post
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Post('');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers App\Controllers\Post::getID
     * @todo   Implement testGetID().
     */
    public function testGetID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::authBlog
     * @todo   Implement testAuthBlog().
     */
    public function testAuthBlog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::showAction
     * @todo   Implement testShowAction().
     */
    public function testShowAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::editAction
     * @todo   Implement testEditAction().
     */
    public function testEditAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::updateAction
     * @todo   Implement testUpdateAction().
     */
    public function testUpdateAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::deleteAction
     * @todo   Implement testDeleteAction().
     */
    public function testDeleteAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::removeAction
     * @todo   Implement testRemoveAction().
     */
    public function testRemoveAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::newAction
     * @todo   Implement testNewAction().
     */
    public function testNewAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Controllers\Post::createAction
     * @todo   Implement testCreateAction().
     */
    public function testCreateAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
